-- CoreTuner Central 0.4.3
-- Execute uma vez no banco PostgreSQL selecionado no EasyPanel.
-- A aplicação também usa SQLAlchemy create_all, mas este arquivo permite criar
-- e revisar explicitamente toda a estrutura antes do primeiro deploy.

BEGIN;

CREATE TABLE IF NOT EXISTS companies (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(160) NOT NULL,
    slug            VARCHAR(120) NOT NULL UNIQUE,
    active          BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_companies_slug ON companies (slug);

CREATE TABLE IF NOT EXISTS users (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id      INTEGER NULL REFERENCES companies(id) ON DELETE SET NULL,
    name            VARCHAR(120) NOT NULL,
    email           VARCHAR(190) NOT NULL UNIQUE,
    password_hash   VARCHAR(300) NOT NULL,
    role            VARCHAR(40) NOT NULL DEFAULT 'viewer',
    active          BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_users_role CHECK (role IN ('platform_admin','company_admin','technician','viewer'))
);

CREATE INDEX IF NOT EXISTS ix_users_company_id ON users (company_id);
CREATE INDEX IF NOT EXISTS ix_users_email ON users (email);

CREATE TABLE IF NOT EXISTS enrollment_tokens (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id      INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    token_hash      VARCHAR(64) NOT NULL UNIQUE,
    expires_at      TIMESTAMPTZ NOT NULL,
    used_at         TIMESTAMPTZ NULL,
    created_by      INTEGER NULL REFERENCES users(id) ON DELETE SET NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_enrollment_tokens_company_id ON enrollment_tokens (company_id);
CREATE INDEX IF NOT EXISTS ix_enrollment_tokens_token_hash ON enrollment_tokens (token_hash);

CREATE TABLE IF NOT EXISTS devices (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id          INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    device_uid          VARCHAR(190) NOT NULL,
    name                VARCHAR(160) NOT NULL,
    hostname            VARCHAR(160) NOT NULL,
    sector              VARCHAR(120) NULL,
    location            VARCHAR(160) NULL,
    manufacturer        VARCHAR(160) NULL,
    model               VARCHAR(160) NULL,
    serial_number       VARCHAR(160) NULL,
    os_name             VARCHAR(160) NULL,
    os_version          VARCHAR(160) NULL,
    agent_version       VARCHAR(40) NULL,
    agent_secret_hash   VARCHAR(64) NOT NULL,
    profile             VARCHAR(80) NULL,
    first_seen          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_seen           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    active              BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_device_company_uid UNIQUE (company_id, device_uid)
);

CREATE INDEX IF NOT EXISTS ix_devices_company_id ON devices (company_id);
CREATE INDEX IF NOT EXISTS ix_devices_company_last_seen ON devices (company_id, last_seen);

CREATE TABLE IF NOT EXISTS telemetry (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id           INTEGER NOT NULL REFERENCES devices(id) ON DELETE CASCADE,
    recorded_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    cpu_percent         DOUBLE PRECISION NULL,
    memory_percent      DOUBLE PRECISION NULL,
    memory_used_gb      DOUBLE PRECISION NULL,
    memory_total_gb     DOUBLE PRECISION NULL,
    disk_percent        DOUBLE PRECISION NULL,
    disk_free_gb        DOUBLE PRECISION NULL,
    disk_total_gb       DOUBLE PRECISION NULL,
    temperature_c       DOUBLE PRECISION NULL,
    uptime_seconds      INTEGER NULL,
    ip_local            VARCHAR(80) NULL,
    network_name        VARCHAR(160) NULL,
    defender_active     BOOLEAN NULL,
    firewall_active     BOOLEAN NULL,
    raw_json            TEXT NULL,
    CONSTRAINT ck_telemetry_cpu CHECK (cpu_percent IS NULL OR (cpu_percent >= 0 AND cpu_percent <= 100)),
    CONSTRAINT ck_telemetry_memory CHECK (memory_percent IS NULL OR (memory_percent >= 0 AND memory_percent <= 100)),
    CONSTRAINT ck_telemetry_disk CHECK (disk_percent IS NULL OR (disk_percent >= 0 AND disk_percent <= 100))
);

CREATE INDEX IF NOT EXISTS ix_telemetry_device_id ON telemetry (device_id);
CREATE INDEX IF NOT EXISTS ix_telemetry_device_recorded ON telemetry (device_id, recorded_at);

CREATE TABLE IF NOT EXISTS alerts (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id          INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    device_id           INTEGER NOT NULL REFERENCES devices(id) ON DELETE CASCADE,
    alert_type          VARCHAR(80) NOT NULL,
    severity            VARCHAR(20) NOT NULL,
    title               VARCHAR(180) NOT NULL,
    message             TEXT NOT NULL,
    status              VARCHAR(20) NOT NULL DEFAULT 'open',
    opened_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_seen_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    acknowledged_at     TIMESTAMPTZ NULL,
    resolved_at         TIMESTAMPTZ NULL,
    CONSTRAINT ck_alerts_severity CHECK (severity IN ('warning','critical')),
    CONSTRAINT ck_alerts_status CHECK (status IN ('open','acknowledged','resolved'))
);

CREATE INDEX IF NOT EXISTS ix_alerts_company_id ON alerts (company_id);
CREATE INDEX IF NOT EXISTS ix_alerts_device_id ON alerts (device_id);
CREATE INDEX IF NOT EXISTS ix_alerts_company_status ON alerts (company_id, status);

CREATE TABLE IF NOT EXISTS audit_logs (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id          INTEGER NULL REFERENCES companies(id) ON DELETE SET NULL,
    actor_user_id       INTEGER NULL REFERENCES users(id) ON DELETE SET NULL,
    device_id           INTEGER NULL REFERENCES devices(id) ON DELETE SET NULL,
    action              VARCHAR(120) NOT NULL,
    details             TEXT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_audit_logs_company_id ON audit_logs (company_id);
CREATE INDEX IF NOT EXISTS ix_audit_logs_created_at ON audit_logs (created_at);

COMMIT;
